config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'

  resources :blog_posts
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :blog_posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :password_confirmation, :current_password])
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController

  def index
    access_key = '2oD7ETB5EsN69WCDoYyFMZIgaMQoViR07wMXxAfMwTg'
    @unsplash_service = UnsplashService.new(access_key)

    @posts = BlogPost.order(created_at: :desc)
    @post_images = {}

    @posts.each do |post|
      images = @unsplash_service.search_photos(post.title)
      @post_images[post.id] = images.first unless images.empty?
    end
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = current_user.blog_posts.new(blog_post_params)
    if @blog_post.save
      redirect_to(blog_posts_path, notice: "Post created successfully!")
    else
      render(:new)
    end
  end

  def edit
    @blog_post = BlogPost.find(params[:id])
  end

  def update
    blog_post = BlogPost.find(params[:id])
    if blog_post.update(blog_post_params)
      redirect_to(blog_posts_path, notice: "Post updated successfully!")
    else
      render(:edit)
    end
  end

  def destroy
    blog_post = BlogPost.find(params[:id])
    if blog_post.destroy
      redirect_to(blog_posts_path, notice: "Page deleted successfully!")
    else
      redirect_to(blog_posts_path, error: "Something went wrong, please try later!")
    end
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blog_posts/edit.html.erb
<%= form_for @blog_post, html: { class: "simple-form" } do |f| %>
  <div class="simple-form-container">
    <h2 class="form-title">Edit Post</h2>
    <div class="form-group">
      <%= f.label :title, "Title*" %>
      <%= f.text_field :title, class: "form-control", style: "width: 100%;" %>
    </div>
    <div class="form-group">
      <%= f.label :content, "Content*" %>
      <%= f.text_field :content, class: "form-control", style: "width: 100%;" %>
    </div>
    <div class="form-actions">
      <%= f.submit "Save", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<style type="text/css">
  .simple-form {
    width: 50%;
    margin: 0 auto;
    border: 2px solid #ccc;
    background-color: #f9f9f9;
    padding: 20px;
  }

  .form-title {
    padding: 20px 0;
  }

  .form-group {
    margin-bottom: 20px;
  }

  .form-control {
    width: 100%;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
  }

  .form-actions {
    text-align: center;
    margin-top: 20px;
  }
</style>

app/views/blog_posts/index.html.erb
<div style="padding: 20px; margin-bottom: 10px;">
  <h2 style="display: inline;">Blog Posts</h2>

  <div class="create-post-btn" style="
    margin-left: 15px;"><%= link_to "New Post", new_blog_post_path, style: "text-decoration: none; color: black;"%></div>
  <% if current_user.present? %>
    <div class="create-post-btn"><%= link_to "Sign out", destroy_user_session_path, method: :delete, style: "text-decoration: none; color: black;"%></div>
  <%end%>
</div>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th>Content</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td>
          <div class="post-details">
            <div class="images">
              <% if @post_images[post.id].present? %>
                <%= image_tag(@post_images[post.id]["urls"]["regular"], size: "150x150") %>
              <% else %>
                <p>-</p>
              <% end %>
            </div>
            <div class="post-title"><%= post.title %></div>
          </div>
        </td>
        <td><%= post.user.email %></td>
        <td><%= post.content %></td>
        <td>
          <%= link_to edit_blog_post_path(post), class: "edit-icon" do %>
            <span class="edit-icon" aria-hidden="true">&#9998;</span>
          <% end %>
          <%= link_to blog_post_path(post), method: :delete, onclick: "confirmDelete(#{post.id})", class: "delete-icon" do %>
            <span class="delete-icon" aria-hidden="true">&#128465;</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<style>
  table {
    border-collapse: collapse;
    width: 100%;
  }
  th, td {
    border: 1px solid black;
    padding: 8px;
    text-align: left;
  }
  th {
    background-color: #f2f2f2; /* Add background color to header cells */
  }
  .edit-icon, .delete-icon {
    cursor: pointer;
    text-decoration: none
  }

  .create-post-btn {
    float: right;
    background-color: #e0e0e0;
    color: #fff;
    border: none;
    padding: 8px 12px;
    border-radius: 15px;
    text-decoration: none;
    cursor: pointer;
    font-size: 15px;
  }
  .create-post-btn:hover {
    background-color: #0056b3;
  }

  .post-details {
    display: flex;
    align-items: center;
  }

  .post-title {
    font-weight: bold;
    margin-right: 10px;
    margin-left: 10px;
  }

  .images {
    width: 50px; /* Set width of image container */
  }

  .images img {
    max-width: 100%;
    height: 50px;
  }
</style>

<script>
  function confirmDelete(postId) {
    if (confirm("Are you sure you want to delete this post?")) {
      window.location.href = "/blog_posts";
    }
  }
</script>

app/views/blog_posts/new.html.erb
<%= form_for @blog_post, html: { class: "simple-form" } do |f| %>
  <div class="simple-form-container">
    <h2 class="form-title">New Post</h2>
    <div class="form-group">
      <%= f.label :title, "Title*", class: "form-label" %>
      <%= f.text_field :title, class: "form-control", required: true %>
    </div>
    <div class="form-group">
      <%= f.label :content, "Content*", class: "form-label" %>
      <%= f.text_area :content, class: "form-control", required: true, rows: 5 %>
    </div>
    <div class="form-actions">
      <%= f.submit "Save", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<style type="text/css">
  .simple-form {
    width: 50%;
    margin: 0 auto;
    border: 2px solid #ccc;
    background-color: #f9f9f9;
    padding: 20px;
  }

  .form-title {
    padding: 20px 0;
    text-align: center;
  }

  .form-group {
    margin-bottom: 20px;
  }

  .form-label {
    display: block;
    margin-bottom: 5px;
  }

  .form-control {
    width: 100%;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
  }

  .form-actions {
    text-align: center;
    margin-top: 20px;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogManagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to Your Blog Application</h1>
<% if user_signed_in? %>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "home_page_btn"%>
<% else %>
  <%= link_to "Sign in", new_user_session_path, class: "home_page_btn"%>
  <%= link_to "Sign up", new_user_registration_path , class: "home_page_btn"%>
<% end %>
<% if user_signed_in? %>
  <div style=" margin-top: 25px;">
    <%= link_to "View Blog Post", blog_posts_path , class: "home_page_btn"%>
  </div>
<%end%>


<style type="text/css">
   .home_page_btn {
    background-color: black;
    color: #fff;
    border: none;
    padding: 8px 12px;
    border-radius: 15px;
    text-decoration: none;
    cursor: pointer;
    font-size: 15px;
  }
  .home_page_btn:hover {
    background-color: #0056b3;
  }
</style>